export const cityName = [
  "Tunis",
  "Sidi Bouzid",
  "Sfax",
  "Sousse",
  "Kairouan",
  "Métouia",
  "Kebili",
  "Sukrah",
  "Gabès",
  "Ariana",
  "Sakiet ed Daier",
  "Gafsa",
  "Msaken",
  "Medenine",
  "Béja",
  "Kasserine",
  "Radès",
  "Hammamet",
  "Tataouine",
  "Monastir",
  "La Marsa",
  "Ben Arous",
  "Sakiet ez Zit",
  "Zarzis",
  "Ben Gardane",
  "Mahdia",
  "Houmt Souk",
  "Fouchana",
  "Le Kram",
  "El Kef",
  "El Hamma",
  "Nabeul",
  "Le Bardo",
  "Djemmal",
  "Korba",
  "Menzel Temime",
  "Ghardimaou",
  "Midoun",
  "Menzel Bourguiba",
  "Manouba",
  "Kélibia",
  "Rass el Djebel",
  "Oued Lill",
  "Moknine",
  "Bir Ali Ben Khalifa",
  "Kelaa Kebira",
  "El Jem",
  "Tebourba",
  "Ksar Hellal",
  "Douz",
  "Bizerte",
  "Jendouba",
  "La Goulette",
  "Jedeïda",
  "Soliman",
  "Hammam Sousse",
  "Sbiba",
  "Tabarka",
  "Sejenane",
  "Metlaoui",
  "Hammam-Lif",
  "Teboulba",
  "Bouhjar",
  "Tozeur",
  "Beni Khiar",
  "Dar Chabanne",
  "Aïne Draham",
  "Bou Salem",
  "Ez Zahra",
  "Kalaa Srira",
  "Skhira",
  "Akouda",
  "El Ksar",
  "Mateur",
  "Siliana",
  "Rhennouch",
  "Dahmani",
  "El Alia",
  "Ar Rudayyif",
  "Mégrine",
  "Ksour Essaf",
  "Zaouiet Sousse",
  "Chebba",
  "Grombalia",
  "Ajim",
  "Feriana",
  "El Maknassi",
  "Beni Khalled",
  "Medjez el Bab",
  "Takelsa",
  "Tabursuq",
  "Ouardenine",
  "Moularès",
  "Nefta",
  "Carthage",
  "Tinja",
  "Zaghouan",
  "Sbeitla",
  "La Mornaghia",
  "Rhar el Melah",
  "Tajerouine",
  "Menzel Abderhaman",
  "Sahline",
  "Mennzel Bou Zelfa",
  "Galaat el Andeless",
  "Banbalah",
  "Bekalta",
  "Mareth",
  "Ghomrassen",
  "Mahires",
  "Goubellat",
  "Gammarth",
  "Bennane",
  "El Guetar",
  "Thala",
  "Hammam el Rhezez",
  "Testour",
  "Bou Arada",
  "Ksibet el Mediouni",
  "Maktar",
  "Messadine",
  "M’dhilla",
  "Seïada",
  "Wadhraf",
  "Bou Arkoub",
  "As Sars",
  "Zriba-Village",
  "Bou Merdès",
  "Er Regueb",
  "Sidi Tabet",
  "Enfida",
  "Rejiche",
  "Ousseltia",
  "Hajeb el Aïoun",
  "Sidi Bou Ali",
  "Gafour",
  "Remada",
  "Khunays",
  "Jerissa",
  "El Haouaria",
  "Agareb",
  "Menzel Kamel",
  "Tazarka",
  "Harqalah",
  "Beni Hassane",
  "Dehiba",
];
