export const secteurName = [
  "Centres d'appels",
  "Formation",
  "Ressources humaines",
  "Ingénierie",
  "Marketing",
  "Informatique",
  "Services et conseil en informatique",
  "Tous secteurs",
  "Télécommunications",
  "Industrie",
  "Technologie de l'information",
  "Commerce",
  "Vente",
  "Transport",
  "Stratégie-Planification",
  "Science",
  "Commerce de détail",
  "Restauration",
  "Recherche",
  "Immobilier",
  "Contrôle Qualité",
  "Achat - Approvisionnement",
  "Pharmaceutiques",
  "Services à la clientèle",
  "Média-Journalisme",
  "Gestion",
  "Juridique",
  "Assurances",
  "Installation-Entretien-Réparation",
  "Santé",
  "Fonction publique",
  "Services vétérinaires",
  "Enseignement",
  "Distribution",
  "Design",
  "Consulting",
  "Construction",
  "Développement des affaires",
  "Biotechnologie",
  "Banque",
  "Administration",
  "Comptabilité",
];
